INSERT INTO `managers` (id, name, age, salary) VALUES (1, 'John', 25, 200);
INSERT INTO `managers` (id, name, age, salary) VALUES (2, 'Nick', 38, 280);
INSERT INTO `managers` (id, name, age, salary) VALUES (3, 'Mike', 42, 300);
INSERT INTO `managers` (id, name, age, salary) VALUES (4, 'Andy', 19, 150);

INSERT INTO `customers` (id, name) VALUES (1, 'Marta');
INSERT INTO `customers` (id, name) VALUES (2, 'Sophie');

